/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cad;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author virajee
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        changeImage();
        setLocationRelativeTo(null);
        setAccessPrivileges();
    }

    //this method is for establishing access privileges
    private void setAccessPrivileges() {
        if (!UserLevel.userLevel.equals("Administrator")) {
            menu_item_registration.setEnabled(false);
            menu_item_password_change.setEnabled(false);
            menu_item_delete_user.setEnabled(false);            
        }        
    }

    //this method is for changing image of the Frame
    private void changeImage() {
        ImageIcon imageicon = new ImageIcon(getClass().getResource("/Icon/home_icon.gif"));
        java.awt.Image image = imageicon.getImage();
        setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_item_xray = new javax.swing.JMenuItem();
        menu_item_ct = new javax.swing.JMenuItem();
        menu_item_exit = new javax.swing.JMenuItem();
        menu_login = new javax.swing.JMenu();
        menu_item_registration = new javax.swing.JMenuItem();
        menu_item_password_change = new javax.swing.JMenuItem();
        menu_item_delete_user = new javax.swing.JMenuItem();
        menu_help = new javax.swing.JMenu();
        menu_item_user_manual = new javax.swing.JMenuItem();
        menu_item_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x-ray.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        menu_file.setText("File");

        menu_item_xray.setText("Upload X-ray");
        menu_item_xray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_xrayActionPerformed(evt);
            }
        });
        menu_file.add(menu_item_xray);

        menu_item_ct.setText("Upload CT ");
        menu_item_ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_ctActionPerformed(evt);
            }
        });
        menu_file.add(menu_item_ct);

        menu_item_exit.setText("Exit");
        menu_item_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_exitActionPerformed(evt);
            }
        });
        menu_file.add(menu_item_exit);

        jMenuBar1.add(menu_file);

        menu_login.setText("Login");

        menu_item_registration.setText("New User Registration");
        menu_item_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_registrationActionPerformed(evt);
            }
        });
        menu_login.add(menu_item_registration);

        menu_item_password_change.setText("Change Password");
        menu_item_password_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_password_changeActionPerformed(evt);
            }
        });
        menu_login.add(menu_item_password_change);

        menu_item_delete_user.setText("Delete User");
        menu_item_delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_delete_userActionPerformed(evt);
            }
        });
        menu_login.add(menu_item_delete_user);

        jMenuBar1.add(menu_login);

        menu_help.setText("Help");

        menu_item_user_manual.setText("User Manual");
        menu_item_user_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_user_manualActionPerformed(evt);
            }
        });
        menu_help.add(menu_item_user_manual);

        menu_item_about.setText("About");
        menu_item_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_aboutActionPerformed(evt);
            }
        });
        menu_help.add(menu_item_about);

        jMenuBar1.add(menu_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_xrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_xrayActionPerformed
        XRayImageUploadForm x = new XRayImageUploadForm();
        this.dispose();
        x.setVisible(true);
    }//GEN-LAST:event_menu_item_xrayActionPerformed

    private void menu_item_ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_ctActionPerformed
        UploadDicomImage u = new UploadDicomImage();
        this.dispose();
        u.setVisible(true);
    }//GEN-LAST:event_menu_item_ctActionPerformed

    private void menu_item_delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_delete_userActionPerformed
        DeleteUser d = new DeleteUser();
        this.dispose();
        d.setVisible(true);
    }//GEN-LAST:event_menu_item_delete_userActionPerformed

    private void menu_item_user_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_user_manualActionPerformed
        Desktop desktop = Desktop.getDesktop();
        try {
            File userManual = new File("D:\\Degree Subject Materials\\Final Project\\Final Document");
            userManual.mkdir();
            File f = new File(userManual, "UserManual.pdf");
            desktop.open(f);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_menu_item_user_manualActionPerformed

    private void menu_item_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_exitActionPerformed
        Login l = new Login();
        this.dispose();
        l.setVisible(true);
    }//GEN-LAST:event_menu_item_exitActionPerformed

    private void menu_item_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_registrationActionPerformed
        NewUserRegistration n = new NewUserRegistration();
        this.dispose();
        n.setVisible(true);
    }//GEN-LAST:event_menu_item_registrationActionPerformed

    private void menu_item_password_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_password_changeActionPerformed
        ChnagePassword c = new ChnagePassword();
        this.dispose();
        c.setVisible(true);
    }//GEN-LAST:event_menu_item_password_changeActionPerformed

    private void menu_item_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_aboutActionPerformed
        About a = new About();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_menu_item_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenuItem menu_item_about;
    private javax.swing.JMenuItem menu_item_ct;
    private javax.swing.JMenuItem menu_item_delete_user;
    private javax.swing.JMenuItem menu_item_exit;
    private javax.swing.JMenuItem menu_item_password_change;
    private javax.swing.JMenuItem menu_item_registration;
    private javax.swing.JMenuItem menu_item_user_manual;
    private javax.swing.JMenuItem menu_item_xray;
    private javax.swing.JMenu menu_login;
    // End of variables declaration//GEN-END:variables
}
