/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cad;

import javax.swing.JOptionPane;

/**
 *
 * @author virajee
 */
public class NewUserRegistration extends javax.swing.JFrame {
 private LoginDB log = null;
    private String reverseword = "";
    Validator v=null;
    /**
     * Creates new form NewUserRegistration
     */
    public NewUserRegistration() {
        initComponents();
        setLocationRelativeTo(null);
        txt_username.grabFocus();
        log = new LoginDB();
        v=new Validator();
    }

    //this method is for refreshing the form
    private void clearFields() {
        txt_username.setText("");
        pwd_pass.setText("");
        pwd_confirmPass.setText("");
        combo_user_level.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        combo_user_level = new javax.swing.JComboBox();
        btn_add_user = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        pwd_pass = new javax.swing.JPasswordField();
        pwd_confirmPass = new javax.swing.JPasswordField();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Username: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Password: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Confirm Password: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("User Level: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, -1));

        combo_user_level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Normal user" }));
        jPanel1.add(combo_user_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 220, -1));

        btn_add_user.setText("Add User");
        btn_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_userActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, -1));

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 80, -1));

        pwd_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwd_passKeyPressed(evt);
            }
        });
        jPanel1.add(pwd_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 220, -1));

        pwd_confirmPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwd_confirmPassKeyPressed(evt);
            }
        });
        jPanel1.add(pwd_confirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_userActionPerformed
        String username = txt_username.getText();
        String pass = new String(pwd_pass.getPassword());
        String confirmPass = new String(pwd_confirmPass.getPassword());
        if (v.isPresent(username) && v.isPresent(pass) && v.isPresent(confirmPass)) {            
            if (log.getLogin(username) == null) {  //check whether the username is already taken or not
                if (pass.equals(confirmPass)) {   //in here it checks whether the enetered passwords in two fields are match each other or not
                    if (v.isValidWithPasswordPolicy(pass)) {  //in here it checks whether the entered password is match with the password policy or not
                        String reversedPass = v.reverseuser_pass(pass);
                        LoginInfo l = new LoginInfo(username, reversedPass, combo_user_level.getSelectedItem().toString());
                        int result = log.addLoginData(l);
                        if (result == 1) {
                            JOptionPane.showMessageDialog(null, "New User Added Successfully");
                            clearFields();
                            txt_username.grabFocus();
                        } else if (result == 0) {
                            JOptionPane.showMessageDialog(null, "Some Error Occurred.New User not Added.");
                        }
                    }else{
                       JOptionPane.showMessageDialog(null, "Password does not Match with the Password Policy");
                       pwd_pass.grabFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Password Confirmation is failed");
                    pwd_confirmPass.grabFocus();
                }
            }else{
               JOptionPane.showMessageDialog(null, "Username is Already Taken");
            }
        }
    }//GEN-LAST:event_btn_add_userActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        clearFields();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
       Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void pwd_confirmPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwd_confirmPassKeyPressed
        if (evt.getKeyCode() == 38) {
            pwd_pass.grabFocus();
        }
    }//GEN-LAST:event_pwd_confirmPassKeyPressed

    private void pwd_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwd_passKeyPressed
       if (evt.getKeyCode() == 10) {
            pwd_confirmPass.grabFocus();
        }
        if (evt.getKeyCode() == 40) {
            pwd_confirmPass.grabFocus();
        }
        if (evt.getKeyCode() == 38) {
            txt_username.grabFocus();
        }
    }//GEN-LAST:event_pwd_passKeyPressed

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
       if (evt.getKeyCode() == 10) {
            pwd_pass.grabFocus();
        }
        if (evt.getKeyCode() == 40) {
            pwd_pass.grabFocus();
        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUserRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_user;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox combo_user_level;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwd_confirmPass;
    private javax.swing.JPasswordField pwd_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
